export const missions = [
  {
    id: 1,
    title: 'SELECT + WHERE — KYC Sweep',
    difficulty: 'Beginner',
    scenario: 'Client Documentation Review',
    concepts: ['SELECT', 'WHERE', 'IN'],
    task: "Find all clients whose kyc_status is 'pending' or 'expired'. Return client_id, full_name, and kyc_status.",
    requiredColumns: ['client_id', 'full_name', 'kyc_status'],
    orderMatters: false,
    starterSQL: "SELECT client_id, full_name, kyc_status\nFROM clients\nWHERE ",
    solutionSQL: "SELECT client_id, full_name, kyc_status\nFROM clients\nWHERE kyc_status IN ('pending', 'expired');",
    hint: "Use WHERE kyc_status IN ('pending', 'expired').",
    explanation: "KYC filtering is the first step in compliance monitoring. A simple WHERE clause helps isolate incomplete or expired client documentation before it becomes an audit issue."
  },
  {
    id: 2,
    title: 'JOIN — Pending KYC With Active Accounts',
    difficulty: 'Beginner',
    scenario: 'Client Documentation Review',
    concepts: ['JOIN', 'WHERE'],
    task: "Find active accounts belonging to clients with pending KYC. Return client_id, full_name, account_id, account_type, and account_status.",
    requiredColumns: ['client_id', 'full_name', 'account_id', 'account_type', 'account_status'],
    orderMatters: false,
    starterSQL: "SELECT c.client_id, c.full_name, a.account_id, a.account_type, a.account_status\nFROM clients c\nJOIN accounts a ON ",
    solutionSQL: "SELECT c.client_id, c.full_name, a.account_id, a.account_type, a.account_status\nFROM clients c\nJOIN accounts a ON c.client_id = a.client_id\nWHERE c.kyc_status = 'pending'\n  AND a.account_status = 'Active';",
    hint: "Join clients to accounts using client_id, then filter kyc_status = 'pending' and account_status = 'Active'.",
    explanation: "JOINs connect business entities. In compliance work, the risk is rarely in one table. You often need client data plus account status to identify real operational exposure."
  },
  {
    id: 3,
    title: 'ORDER BY — Large Transaction Review',
    difficulty: 'Beginner',
    scenario: 'Transaction Monitoring',
    concepts: ['WHERE', 'ORDER BY'],
    task: 'Find all transactions above 10000 and sort them from largest to smallest. Return transaction_id, account_id, amount, and transaction_type.',
    requiredColumns: ['transaction_id', 'account_id', 'amount', 'transaction_type'],
    orderMatters: true,
    starterSQL: "SELECT transaction_id, account_id, amount, transaction_type\nFROM transactions\nWHERE ",
    solutionSQL: "SELECT transaction_id, account_id, amount, transaction_type\nFROM transactions\nWHERE amount > 10000\nORDER BY amount DESC;",
    hint: 'Use WHERE amount > 10000 and ORDER BY amount DESC.',
    explanation: "Sorting large transactions by value helps analysts prioritize review. In real compliance queues, the largest exceptions often get reviewed first."
  },
  {
    id: 4,
    title: 'GROUP BY — Flags by Severity',
    difficulty: 'Beginner',
    scenario: 'Audit Readiness',
    concepts: ['GROUP BY', 'COUNT'],
    task: 'Count compliance flags by severity. Return severity and flag_count.',
    requiredColumns: ['severity', 'flag_count'],
    orderMatters: false,
    starterSQL: "SELECT severity, COUNT(*) AS flag_count\nFROM compliance_flags\nGROUP BY ",
    solutionSQL: "SELECT severity, COUNT(*) AS flag_count\nFROM compliance_flags\nGROUP BY severity;",
    hint: 'Use COUNT(*) and GROUP BY severity. Alias the count as flag_count.',
    explanation: "GROUP BY turns raw exceptions into reporting metrics. This is how compliance teams summarize risk volume for management reporting."
  },
  {
    id: 5,
    title: 'JOIN + GROUP BY — Advisor Risk Workload',
    difficulty: 'Intermediate',
    scenario: 'Advisor Risk Dashboard',
    concepts: ['JOIN', 'GROUP BY', 'COUNT'],
    task: 'Count unresolved compliance reviews by advisor. Return advisor_name and open_issue_count.',
    requiredColumns: ['advisor_name', 'open_issue_count'],
    orderMatters: false,
    starterSQL: "SELECT ad.advisor_name, COUNT(*) AS open_issue_count\nFROM compliance_reviews cr\nJOIN accounts a ON ",
    solutionSQL: "SELECT ad.advisor_name, COUNT(*) AS open_issue_count\nFROM compliance_reviews cr\nJOIN accounts a ON cr.account_id = a.account_id\nJOIN clients c ON a.client_id = c.client_id\nJOIN advisors ad ON c.advisor_id = ad.advisor_id\nWHERE cr.review_status IN ('Open', 'In Progress')\nGROUP BY ad.advisor_name;",
    hint: "Join reviews → accounts → clients → advisors, then filter review_status IN ('Open', 'In Progress').",
    explanation: "This is a workload query. It shows who has unresolved compliance items, which supports prioritization, staffing, and accountability."
  },
  {
    id: 6,
    title: 'HAVING — Advisors With Multiple Open Issues',
    difficulty: 'Intermediate',
    scenario: 'Advisor Risk Dashboard',
    concepts: ['HAVING', 'GROUP BY'],
    task: 'Find advisors with more than 1 unresolved compliance review. Return advisor_name and open_issue_count.',
    requiredColumns: ['advisor_name', 'open_issue_count'],
    orderMatters: false,
    starterSQL: "SELECT ad.advisor_name, COUNT(*) AS open_issue_count\nFROM compliance_reviews cr\nJOIN accounts a ON cr.account_id = a.account_id\n",
    solutionSQL: "SELECT ad.advisor_name, COUNT(*) AS open_issue_count\nFROM compliance_reviews cr\nJOIN accounts a ON cr.account_id = a.account_id\nJOIN clients c ON a.client_id = c.client_id\nJOIN advisors ad ON c.advisor_id = ad.advisor_id\nWHERE cr.review_status IN ('Open', 'In Progress')\nGROUP BY ad.advisor_name\nHAVING COUNT(*) > 1;",
    hint: 'Use the same query as Mission 5, then add HAVING COUNT(*) > 1 after GROUP BY.',
    explanation: "WHERE filters rows before grouping. HAVING filters grouped results after aggregation. That is useful when reporting only material risk concentrations."
  },
  {
    id: 7,
    title: 'LEFT JOIN + NULL — Missing Reviews',
    difficulty: 'Intermediate',
    scenario: 'Audit Readiness',
    concepts: ['LEFT JOIN', 'NULL'],
    task: 'Find active accounts that do not have any compliance review. Return account_id, account_type, and account_status.',
    requiredColumns: ['account_id', 'account_type', 'account_status'],
    orderMatters: false,
    starterSQL: "SELECT a.account_id, a.account_type, a.account_status\nFROM accounts a\nLEFT JOIN compliance_reviews cr ON ",
    solutionSQL: "SELECT a.account_id, a.account_type, a.account_status\nFROM accounts a\nLEFT JOIN compliance_reviews cr ON a.account_id = cr.account_id\nWHERE a.account_status = 'Active'\n  AND cr.review_id IS NULL;",
    hint: 'LEFT JOIN accounts to reviews, then find rows where cr.review_id IS NULL.',
    explanation: "LEFT JOIN plus IS NULL is the classic missing-data check. It finds what should exist but does not, which is critical for audit readiness."
  },
  {
    id: 8,
    title: 'Reconciliation — Unbalanced Journal Entries',
    difficulty: 'Intermediate',
    scenario: 'Reconciliation and Accounting',
    concepts: ['Reconciliation', 'WHERE'],
    task: 'Find journal entries where debit_amount does not equal credit_amount. Return journal_id, transaction_id, debit_amount, and credit_amount.',
    requiredColumns: ['journal_id', 'transaction_id', 'debit_amount', 'credit_amount'],
    orderMatters: false,
    starterSQL: "SELECT journal_id, transaction_id, debit_amount, credit_amount\nFROM journal_entries\nWHERE ",
    solutionSQL: "SELECT journal_id, transaction_id, debit_amount, credit_amount\nFROM journal_entries\nWHERE debit_amount <> credit_amount;",
    hint: 'Use WHERE debit_amount <> credit_amount.',
    explanation: "Debit and credit mismatches are reconciliation exceptions. SQL can quickly identify accounting records that need investigation."
  },
  {
    id: 9,
    title: 'CASE — Transaction Risk Bands',
    difficulty: 'Intermediate',
    scenario: 'Transaction Monitoring',
    concepts: ['CASE', 'Classification'],
    task: "Classify transactions as Low if amount < 5000, Medium if amount is between 5000 and 9999.99, and High if amount >= 10000. Return transaction_id, amount, and risk_band.",
    requiredColumns: ['transaction_id', 'amount', 'risk_band'],
    orderMatters: false,
    starterSQL: "SELECT transaction_id, amount,\n  CASE\n    WHEN amount < 5000 THEN 'Low'\n",
    solutionSQL: "SELECT transaction_id, amount,\n  CASE\n    WHEN amount < 5000 THEN 'Low'\n    WHEN amount >= 5000 AND amount < 10000 THEN 'Medium'\n    ELSE 'High'\n  END AS risk_band\nFROM transactions;",
    hint: "Use CASE WHEN amount < 5000 THEN 'Low' WHEN amount < 10000 THEN 'Medium' ELSE 'High' END AS risk_band.",
    explanation: "CASE statements turn raw numbers into business labels. This is how analysts create risk bands, priority flags, and dashboard categories."
  },
  {
    id: 10,
    title: 'Final Boss — Compliance Exception Report',
    difficulty: 'Advanced',
    scenario: 'Boss Mode',
    concepts: ['Multi-table JOIN', 'Exception Reporting'],
    task: 'Create a report joining clients, advisors, accounts, transactions, and compliance_flags. Show unreviewed compliance flags only. Return client_name, advisor_name, account_type, transaction_id, amount, flag_type, and severity.',
    requiredColumns: [
      { name: 'client_name', aliases: ['full_name'] },
      'advisor_name', 'account_type', 'transaction_id', 'amount', 'flag_type', 'severity'
    ],
    orderMatters: false,
    starterSQL: "SELECT c.full_name AS client_name, ad.advisor_name, a.account_type,\n       t.transaction_id, t.amount, cf.flag_type, cf.severity\nFROM compliance_flags cf\n",
    solutionSQL: "SELECT c.full_name AS client_name, ad.advisor_name, a.account_type,\n       t.transaction_id, t.amount, cf.flag_type, cf.severity\nFROM compliance_flags cf\nJOIN transactions t ON cf.transaction_id = t.transaction_id\nJOIN accounts a ON t.account_id = a.account_id\nJOIN clients c ON a.client_id = c.client_id\nJOIN advisors ad ON c.advisor_id = ad.advisor_id\nWHERE cf.reviewed = 0;",
    hint: 'Start from compliance_flags, join to transactions, accounts, clients, and advisors. Filter reviewed = 0.',
    explanation: "The final report combines source data into a compliance exception view. This mirrors real analyst work: connect clients, advisors, accounts, activity, and flags into one audit-ready output."
  },
  {
    id: 11,
    title: 'Subquery — Clients with Unreviewed Flags',
    difficulty: 'Intermediate',
    scenario: 'Client Documentation Review',
    concepts: ['Subquery', 'IN'],
    task: "Use a subquery to find clients who have at least one unreviewed compliance flag linked to their transactions. Return client_id, full_name, and risk_rating.",
    requiredColumns: ['client_id', 'full_name', 'risk_rating'],
    orderMatters: false,
    starterSQL: "SELECT client_id, full_name, risk_rating\nFROM clients\nWHERE client_id IN (\n  SELECT DISTINCT ",
    solutionSQL: "SELECT client_id, full_name, risk_rating\nFROM clients\nWHERE client_id IN (\n  SELECT DISTINCT c2.client_id\n  FROM clients c2\n  JOIN accounts a ON c2.client_id = a.client_id\n  JOIN transactions t ON a.account_id = t.account_id\n  JOIN compliance_flags cf ON t.transaction_id = cf.transaction_id\n  WHERE cf.reviewed = 0\n);",
    hint: "Build an inner query walking clients → accounts → transactions → compliance_flags WHERE reviewed = 0, then wrap it: WHERE client_id IN (...).",
    explanation: "Subqueries nest one query inside another. The inner query identifies at-risk client IDs; the outer query fetches their details. This separates filter logic from presentation logic."
  },
  {
    id: 12,
    title: 'DISTINCT — High-Risk Client Provinces',
    difficulty: 'Beginner',
    scenario: 'Advisor Risk Dashboard',
    concepts: ['DISTINCT', 'ORDER BY'],
    task: "Find the distinct provinces that contain at least one high-risk rated client. Return province sorted alphabetically.",
    requiredColumns: ['province'],
    orderMatters: true,
    starterSQL: "SELECT DISTINCT province\nFROM clients\nWHERE ",
    solutionSQL: "SELECT DISTINCT province\nFROM clients\nWHERE risk_rating = 'High'\nORDER BY province;",
    hint: "Use SELECT DISTINCT province FROM clients WHERE risk_rating = 'High' ORDER BY province.",
    explanation: "DISTINCT removes duplicate rows. When mapping geographic risk, you need unique jurisdictions, not one row per client. This feeds into regional risk reporting."
  },
  {
    id: 13,
    title: 'BETWEEN — Mid-Range Transaction Screening',
    difficulty: 'Beginner',
    scenario: 'Transaction Monitoring',
    concepts: ['BETWEEN'],
    task: "Find transactions with amounts between 5000 and 15000 inclusive — a bracket that can escape automated high-value screening. Return transaction_id, amount, and transaction_type.",
    requiredColumns: ['transaction_id', 'amount', 'transaction_type'],
    orderMatters: false,
    starterSQL: "SELECT transaction_id, amount, transaction_type\nFROM transactions\nWHERE ",
    solutionSQL: "SELECT transaction_id, amount, transaction_type\nFROM transactions\nWHERE amount BETWEEN 5000 AND 15000;",
    hint: 'Use WHERE amount BETWEEN 5000 AND 15000.',
    explanation: "BETWEEN is inclusive on both ends. Compliance teams screen mid-range amounts because some clients deliberately keep transactions just below automated thresholds — a practice called structuring."
  },
  {
    id: 14,
    title: 'NOT IN — Clients with No Review History',
    difficulty: 'Intermediate',
    scenario: 'Audit Readiness',
    concepts: ['NOT IN', 'Subquery'],
    task: "Find clients who have no accounts with any compliance review on record. Return client_id, full_name, and province.",
    requiredColumns: ['client_id', 'full_name', 'province'],
    orderMatters: false,
    starterSQL: "SELECT client_id, full_name, province\nFROM clients\nWHERE client_id NOT IN (\n  SELECT DISTINCT ",
    solutionSQL: "SELECT client_id, full_name, province\nFROM clients\nWHERE client_id NOT IN (\n  SELECT DISTINCT c2.client_id\n  FROM clients c2\n  JOIN accounts a ON c2.client_id = a.client_id\n  JOIN compliance_reviews cr ON a.account_id = cr.account_id\n);",
    hint: "Use WHERE client_id NOT IN (SELECT DISTINCT c2.client_id FROM clients c2 JOIN accounts a ON c2.client_id = a.client_id JOIN compliance_reviews cr ON a.account_id = cr.account_id).",
    explanation: "NOT IN finds gaps — entities that should appear in a related table but do not. Missing review history is itself a compliance exception: every active client should have a documented review trail."
  },
  {
    id: 15,
    title: 'UNION — Combined Suspicious Transaction Queue',
    difficulty: 'Intermediate',
    scenario: 'Transaction Monitoring',
    concepts: ['UNION', 'Labeling'],
    task: "Build a unified suspicious-transaction list combining large deposits over 50000 with reversed transactions. Label each with a category. Return transaction_id, amount, transaction_status, and category.",
    requiredColumns: ['transaction_id', 'amount', 'transaction_status', 'category'],
    orderMatters: false,
    starterSQL: "SELECT transaction_id, amount, transaction_status, 'Large Deposit' AS category\nFROM transactions\nWHERE amount > 50000 AND transaction_type = 'Deposit'\nUNION\n",
    solutionSQL: "SELECT transaction_id, amount, transaction_status, 'Large Deposit' AS category\nFROM transactions\nWHERE amount > 50000 AND transaction_type = 'Deposit'\nUNION\nSELECT transaction_id, amount, transaction_status, 'Reversed' AS category\nFROM transactions\nWHERE transaction_status = 'Reversed';",
    hint: "Use two SELECT statements joined with UNION. Add a literal string 'Large Deposit' or 'Reversed' as the category column in each branch.",
    explanation: "UNION merges results from two queries and removes duplicates. It is ideal for building unified exception queues from separate screening criteria — combining categories that analysts triage together."
  },
  {
    id: 16,
    title: 'CTE — Accounts with Multiple Compliance Flags',
    difficulty: 'Advanced',
    scenario: 'Reconciliation and Accounting',
    concepts: ['CTE', 'WITH'],
    task: "Use a Common Table Expression to count compliance flags per account, then return only accounts with 2 or more flags. Return account_id and flag_count.",
    requiredColumns: ['account_id', 'flag_count'],
    orderMatters: false,
    starterSQL: "WITH flag_counts AS (\n  SELECT t.account_id, COUNT(*) AS flag_count\n  FROM compliance_flags cf\n  JOIN transactions t ON cf.transaction_id = t.transaction_id\n  GROUP BY t.account_id\n)\n",
    solutionSQL: "WITH flag_counts AS (\n  SELECT t.account_id, COUNT(*) AS flag_count\n  FROM compliance_flags cf\n  JOIN transactions t ON cf.transaction_id = t.transaction_id\n  GROUP BY t.account_id\n)\nSELECT account_id, flag_count\nFROM flag_counts\nWHERE flag_count >= 2;",
    hint: "Complete the CTE then add: SELECT account_id, flag_count FROM flag_counts WHERE flag_count >= 2.",
    explanation: "CTEs let you name an intermediate result and reference it like a table. Accounts with multiple flags indicate concentrated risk warranting prioritised review."
  },
  {
    id: 17,
    title: 'EXISTS — High-Risk Clients Under Active Review',
    difficulty: 'Advanced',
    scenario: 'Advisor Risk Dashboard',
    concepts: ['EXISTS', 'Correlated Subquery'],
    task: "Find high-risk clients who currently have at least one open compliance review. Return client_id, full_name, and risk_rating.",
    requiredColumns: ['client_id', 'full_name', 'risk_rating'],
    orderMatters: false,
    starterSQL: "SELECT c.client_id, c.full_name, c.risk_rating\nFROM clients c\nWHERE c.risk_rating = 'High'\n  AND EXISTS (\n    SELECT 1\n    ",
    solutionSQL: "SELECT c.client_id, c.full_name, c.risk_rating\nFROM clients c\nWHERE c.risk_rating = 'High'\n  AND EXISTS (\n    SELECT 1\n    FROM accounts a\n    JOIN compliance_reviews cr ON a.account_id = cr.account_id\n    WHERE a.client_id = c.client_id\n      AND cr.review_status = 'Open'\n  );",
    hint: "Use WHERE c.risk_rating = 'High' AND EXISTS (SELECT 1 FROM accounts a JOIN compliance_reviews cr ON a.account_id = cr.account_id WHERE a.client_id = c.client_id AND cr.review_status = 'Open').",
    explanation: "EXISTS returns true as soon as the correlated subquery finds one matching row. Combined with risk filters, it pinpoints the highest-priority clients requiring immediate compliance attention."
  },
  {
    id: 18,
    title: 'AVG — Transaction Averages by Type',
    difficulty: 'Beginner',
    scenario: 'Transaction Monitoring',
    concepts: ['AVG', 'ROUND', 'GROUP BY'],
    task: "Calculate the average transaction amount for each transaction type. Return transaction_type and avg_amount rounded to 2 decimal places.",
    requiredColumns: ['transaction_type', 'avg_amount'],
    orderMatters: false,
    starterSQL: "SELECT transaction_type, ROUND(AVG(amount), 2) AS avg_amount\nFROM transactions\nGROUP BY ",
    solutionSQL: "SELECT transaction_type, ROUND(AVG(amount), 2) AS avg_amount\nFROM transactions\nGROUP BY transaction_type;",
    hint: "Use SELECT transaction_type, ROUND(AVG(amount), 2) AS avg_amount FROM transactions GROUP BY transaction_type.",
    explanation: "AVG is an aggregate like COUNT and SUM. Rounding keeps precision clean for reports. Comparing averages by transaction type helps spot categories where amounts are unusually high."
  },
  {
    id: 19,
    title: 'Date Filter — Overdue Compliance Reviews',
    difficulty: 'Intermediate',
    scenario: 'Audit Readiness',
    concepts: ['Date Filtering', 'String Comparison'],
    task: "Find compliance reviews opened before 2025-01-01 that are still not closed. Return review_id, account_id, review_date, issue_type, and review_status.",
    requiredColumns: ['review_id', 'account_id', 'review_date', 'issue_type', 'review_status'],
    orderMatters: false,
    starterSQL: "SELECT review_id, account_id, review_date, issue_type, review_status\nFROM compliance_reviews\nWHERE review_date < '2025-01-01'\n  AND ",
    solutionSQL: "SELECT review_id, account_id, review_date, issue_type, review_status\nFROM compliance_reviews\nWHERE review_date < '2025-01-01'\n  AND review_status != 'Closed';",
    hint: "Use WHERE review_date < '2025-01-01' AND review_status != 'Closed'.",
    explanation: "Date filtering is fundamental in compliance. Reviews older than a year with no resolution signal process failures regulators scrutinise closely. ISO date text (YYYY-MM-DD) orders correctly with standard string comparison."
  },
  {
    id: 20,
    title: 'Final Boss II — Advisor Risk Dashboard',
    difficulty: 'Advanced',
    scenario: 'Boss Mode',
    concepts: ['CTE', 'Multi-table JOIN', 'GROUP BY', 'ORDER BY'],
    task: "Build an executive summary using a CTE. For each advisor, count open and in-progress compliance reviews by severity. Return advisor_name, severity, and issue_count ordered by advisor_name then severity.",
    requiredColumns: ['advisor_name', 'severity', 'issue_count'],
    orderMatters: true,
    starterSQL: "WITH advisor_issues AS (\n  SELECT ad.advisor_name, cr.severity, COUNT(*) AS issue_count\n  FROM advisors ad\n  JOIN clients c ON ad.advisor_id = c.advisor_id\n",
    solutionSQL: "WITH advisor_issues AS (\n  SELECT ad.advisor_name, cr.severity, COUNT(*) AS issue_count\n  FROM advisors ad\n  JOIN clients c ON ad.advisor_id = c.advisor_id\n  JOIN accounts a ON c.client_id = a.client_id\n  JOIN compliance_reviews cr ON a.account_id = cr.account_id\n  WHERE cr.review_status IN ('Open', 'In Progress')\n  GROUP BY ad.advisor_name, cr.severity\n)\nSELECT advisor_name, severity, issue_count\nFROM advisor_issues\nORDER BY advisor_name, severity;",
    hint: "Complete the CTE by adding the remaining JOINs (accounts, compliance_reviews), filter WHERE review_status IN ('Open','In Progress'), GROUP BY both columns, then SELECT from it with ORDER BY.",
    explanation: "CTEs combined with multi-table JOINs produce executive dashboards from normalised data. This mirrors real compliance reporting: link advisors through clients and accounts to their open issues, aggregate by severity, sort for readability."
  }
];
